# Generated by Django 6.0.4 on 2026-04-19 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=280)),
                ('port', models.IntegerField(default=443)),
                ('etat', models.CharField(default='UNKNOWN', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_serie', models.CharField(max_length=280)),
                ('subject', models.CharField(max_length=280)),
                ('date_debut', models.DateTimeField()),
                ('date_expiration', models.DateTimeField()),
                ('algo_sign', models.CharField(max_length=280)),
                ('alg_pub_key', models.CharField(max_length=280)),
                ('empreinte', models.CharField(max_length=280)),
                ('status', models.CharField(max_length=50)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.host')),
            ],
        ),
    ]
