# Generated by Django 6.0.4 on 2026-04-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_certificat_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificat',
            name='status',
        ),
    ]
